---
language: python
python:
  - '3.4'
  - '3.3'
  - '2.7'
services:
  - elasticsearch
before_install:
  - psql -c 'create database froide;' -U postgres
  - phantomjs --version
  - phantomjs --webdriver= &
install:
  - pip install -r requirements-test.txt
  - pip install psycopg2 coveralls
  - pip install -e .
script:
  - export DATABASE_URL=postgres://postgres@127.0.0.1/froide
  - make test

branches:
  only:
    - master

notifications:
  webhooks: http://pm.codeforhawaii.org/projects/45ccea1a-302d-42fa-a3b5-2cf7b3a599bc/status
